# Generated by Django 3.2.8 on 2021-10-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=128, unique=True)),
                ('company_owner', models.CharField(max_length=64)),
                ('company_hq', models.TextField()),
                ('company_prod', models.TextField()),
                ('company_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=64)),
                ('catalogue_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Switchgear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('serial_no', models.CharField(max_length=32)),
                ('shipped', models.BooleanField(default=False)),
                ('ready_to_ship', models.BooleanField(default=False)),
                ('req_shipment', models.DateField()),
                ('actual_shipment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SwitchgearParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('par_a', models.IntegerField()),
                ('par_ka', models.IntegerField()),
                ('par_v', models.IntegerField()),
                ('par_ui', models.IntegerField()),
                ('par_hz', models.IntegerField()),
                ('par_grid', models.CharField(max_length=8)),
                ('par_protection', models.IntegerField()),
                ('par_ip', models.IntegerField()),
                ('par_ik', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('working_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchgearComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.IntegerField()),
                ('amount_missing', models.IntegerField()),
                ('serial_number', models.CharField(max_length=64)),
                ('supplier', models.CharField(max_length=64)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker_app.component')),
                ('switchgear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker_app.switchgear')),
            ],
        ),
        migrations.AddField(
            model_name='switchgear',
            name='components',
            field=models.ManyToManyField(through='tracker_app.SwitchgearComponents', to='tracker_app.Component'),
        ),
        migrations.AddField(
            model_name='switchgear',
            name='made_by',
            field=models.ManyToManyField(to='tracker_app.Worker'),
        ),
        migrations.AddField(
            model_name='switchgear',
            name='order_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker_app.order'),
        ),
        migrations.AddField(
            model_name='switchgear',
            name='switchgear_parameters',
            field=models.ManyToManyField(to='tracker_app.SwitchgearParameters'),
        ),
        migrations.AddField(
            model_name='order',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker_app.worker'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker_app.client'),
        ),
    ]
