# Generated by Django 3.2.8 on 2021-10-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_auto_20211012_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
