# Generated by Django 3.2.8 on 2021-10-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0011_alter_switchgear_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchgear',
            name='req_shipment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
