# Generated by Django 3.2.8 on 2021-10-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0012_alter_switchgear_req_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchgear',
            name='req_shipment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
