# Generated by Django 3.2.8 on 2021-10-16 13:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0013_alter_switchgear_req_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/logos/'), upload_to=''),
        ),
    ]
