# Generated by Django 3.2.8 on 2021-10-19 10:58

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tracker_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0017_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchgearPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/logos/'), upload_to=tracker_app.models.switchgear_photos_directory_path)),
                ('ref_switchgear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker_app.switchgear')),
            ],
        ),
        migrations.AddField(
            model_name='switchgear',
            name='photos',
            field=models.ManyToManyField(to='tracker_app.SwitchgearPhotos'),
        ),
    ]
