# Generated by Django 3.2.8 on 2021-10-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0018_auto_20211019_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchgear',
            name='has_photos',
            field=models.BooleanField(default=False),
        ),
    ]
