# Generated by Django 3.2.8 on 2021-10-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_auto_20211012_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_hq',
            new_name='hq',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_prod',
            new_name='prod',
        ),
        migrations.RemoveField(
            model_name='company',
            name='login',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
    ]
