# Generated by Django 3.2.8 on 2021-10-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0006_auto_20211012_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchgear',
            name='actual_shipment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='switchgear',
            name='req_shipment',
            field=models.DateField(null=True),
        ),
    ]
