# Generated by Django 3.2.8 on 2021-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0010_auto_20211012_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchgear',
            name='serial_no',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
